In [1]:
# https://youtu.be/Z_ikDlimN6A?si=3oIZV-eHwSdTRPCZ&t=4695

import torch

print(torch.__version__)


2.1.0


# Introduction to Tensors

## Creating Tensors

Pytorch tensors are created using torch.Tensor()

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [6]:
# Get tensor back as python int
scalar.item()

7

In [8]:
# Vector

vector = torch.tensor([7,7])
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [13]:
# MATRIX

MATRIX = torch.tensor([[7,8], [2,3]])
MATRIX.ndim

2

In [14]:
MATRIX[0]

tensor([7, 8])

In [18]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3], [3,4,5], [2,4,5]]])
TENSOR.ndim

3

In [20]:
TENSOR.shape # 1 times a 3x3 Tensor
# outer bracket matches with 1
# middle bracket matches with 3
# most inner bracket 3 (3)

torch.Size([1, 3, 3])

<img height="200px" src="../images/tensor_dimensions.png">

![]('../images/tensor_dimensions.png')

[]('../images/tensor_dimensions')

## Random Tensors

To initialize the Weights and Biases.
We use Random Tensors and then with the data we update the Tensors

In [22]:
# Creating a random tensor of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4681, 0.0666, 0.7705, 0.1733],
        [0.8034, 0.6467, 0.7961, 0.6215],
        [0.2239, 0.1333, 0.8121, 0.6739]])

In [23]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [30]:
# Zero and ones

zeros = torch.zeros(3,4)
ones = torch.ones(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])